### ISSUE TITLE
t.omitBy is not a function

### ISSUE THREAD

**Issue by phonist** [epam/pipeline-builder#39]
Hi, i follow the tutorial, and when i try to execute the library of pipeline.min.js, it shows up this error in chrome devTool, by the way i'm using <script> method to import those libraries, thanks and regards, :)
**Uncaught TypeError: t.omitBy is not a function
    at n.value (VisualStep.js:101)
    at n.value (VisualStep.js:71)
    at n (VisualStep.js:44)
    at n (VisualGroup.js:14)
    at new n (VisualWorkflow.js:12)
    at tn (Visualizer.js:39)
    at n (Visualizer.js:393)
    at e.value (Visualizer.js:412)**
    at e.value (Visualizer.js:258)
    at files:145

**Comment by sidoruka** [comment]
Hi @RuJyi , thanks for pointing this out.
This issues seems to be caused by PR #26 which changed a set of dependencies to be loaded.
Fixed in 3753e742645224727a5a4f389df688a6f3149bd3 ([link-library.md](https://github.com/epam/pipeline-builder/blob/dev/docs/tutorials/link-library.md))
Only following imports shall be included into `<script>` tag

```html
<link rel="stylesheet" href="dist/pipeline.min.css">
<script src="node_modules/jquery/dist/jquery.min.js"></script>
<script src="node_modules/lodash/lodash.js"></script>
<script src="dist/pipeline.min.js"></script>
```

Could you please verify, does it fix this issue?
